need_number('ath9k_workaround.blackout_wait')
need_number('ath9k_workaround.network_wait')
need_number('ath9k_workaround.reboot_wait')
need_number('ath9k_workaround.uptime_wait')
need_number('ath9k_workaround.reset_wait')
need_number('ath9k_workaround.step_size')
