#!/usr/bin/lua
local fs = require('nixio.fs')
local uci = require('luci.model.uci').cursor()
local site = require 'gluon.site_config'

local min_uptime_secs = 600

if os.execute("pgrep respondd") ~= 0 and tonumber(fs.readfile('/proc/uptime'):match('^([^ ]+) ')) > min_uptime_secs then 
  io.popen('logger -s -t respondd-workaround -p local0.info "failure detected. restarting respondd..."')
  io.popen("/etc/init.d/gluon-respondd start")                    
end

